import type { Product } from "./types"

export const sampleProducts: Product[] = [
  {
    id: "1",
    name: "Premium Cotton T-Shirt",
    description:
      "Soft, breathable cotton t-shirt perfect for everyday wear. Made from 100% organic cotton with a comfortable fit.",
    price: 49,
    images: ["/premium-white-cotton-t-shirt.jpg", "/premium-white-cotton-t-shirt-back-view.jpg", "/premium-white-cotton-t-shirt-detail.jpg"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    category: "T-Shirts",
    inStock: true,
    featured: true,
  },
  {
    id: "2",
    name: "Classic Denim Jacket",
    description: "Timeless denim jacket crafted from premium denim. Features classic styling with modern comfort.",
    price: 129,
    images: ["/classic-blue-denim-jacket.png", "/classic-blue-denim-jacket-worn.jpg", "/classic-blue-denim-jacket-details.jpg"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    category: "Jackets",
    inStock: true,
    featured: true,
  },
  {
    id: "3",
    name: "Elegant Silk Blouse",
    description:
      "Luxurious silk blouse perfect for professional and casual settings. Smooth texture with elegant drape.",
    price: 89,
    images: ["/elegant-white-silk-blouse.jpg", "/elegant-white-silk-blouse-styled.jpg", "/elegant-white-silk-blouse-fabric-detail.jpg"],
    sizes: ["XS", "S", "M", "L", "XL"],
    category: "Blouses",
    inStock: true,
    featured: false,
  },
  {
    id: "4",
    name: "Comfortable Joggers",
    description: "Ultra-comfortable joggers made from soft cotton blend. Perfect for lounging or light exercise.",
    price: 69,
    images: ["/comfortable-gray-joggers.jpg", "/comfortable-gray-joggers-worn.jpg", "/comfortable-gray-joggers-detail.jpg"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    category: "Pants",
    inStock: true,
    featured: false,
  },
  {
    id: "5",
    name: "Wool Blend Sweater",
    description: "Cozy wool blend sweater perfect for cooler weather. Soft texture with excellent warmth retention.",
    price: 99,
    images: ["/cozy-beige-wool-sweater.jpg", "/cozy-beige-wool-sweater-styled.jpg", "/cozy-beige-wool-sweater-texture.jpg"],
    sizes: ["XS", "S", "M", "L", "XL"],
    category: "Sweaters",
    inStock: false,
    featured: true,
  },
  {
    id: "6",
    name: "Summer Dress",
    description: "Light and airy summer dress perfect for warm weather. Flowy design with comfortable fit.",
    price: 79,
    images: ["/light-blue-summer-dress.jpg", "/light-blue-summer-dress-worn.jpg", "/placeholder.svg?height=600&width=600"],
    sizes: ["XS", "S", "M", "L", "XL"],
    category: "Dresses",
    inStock: true,
    featured: false,
  },
]
